blog/urls.py
from django.urls import path
from blog.views import post_detail, PostList, SearchPostCategoryView

# app_name

app_name = 'blog'

# Create your urls here.

urlpatterns = [
    path('', PostList.as_view(), name='allblogs'),
    path('<slug:slug>/', post_detail, name='post_detail'),
    path('category/<category>/', SearchPostCategoryView.as_view(), name='post_list_by_category'),
]

ecommerce_pharmacy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import about_view, service_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('search.urls', namespace='search')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('about/', about_view, name='about'),
    path('services/', service_view, name='services'),
    path('contact/', include('contact.urls', namespace='contact')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# django admin site custom header and title
admin.site.site_header = "PHARMACY::ONLINE STORE:: ADMIN"
admin.site.site_title  = "PHARMACY::ONLINE STORE:: ADMIN PORTAL"
admin.site.index_title = "WELCOME TO PHARMACY::ONLINE STORE:: ADMINISTRATION"

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class PostCategory(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'post_category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_list_by_category', kwargs={
            'slug': self.slug
        })


class PostQuerySet(models.query.QuerySet):
    def status(self):
        return self.filter(status=1)

    def category(self, query):
        return self.filter(status=1, category=query)

    def search(self, query):
        lookups = (Q(title__icontains=query) |
                   Q(author__icontains=query) |
                   Q(content__icontains=query) |
                   Q(category__name__icontains=query)
                   )

        return self.filter(lookups).distinct()


class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().status()

    def get_by_id(self, id):
        # Product.objects == self.get_queryset()
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().status().search(query)

    def category(self, query):
        return self.get_queryset().category(query)


class Post(models.Model):
    category = models.ForeignKey(
        PostCategory, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now=True)
    content = RichTextUploadingField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    objects = PostManager()

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = RichTextUploadingField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blog/forms.py
from django import forms
from blog.models import Post, Comment
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from ckeditor_uploader.widgets import CKEditorUploadingWidget


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'category', 'slug', 'author', 'content', 'status')
        widgets = {
            'content': CKEditorUploadingWidget(),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'name' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder':'Enter your name'}),
            'email' : forms.EmailInput(attrs={'class' : 'form-control', 'placeholder':'Enter your email'}),
            'body': CKEditorUploadingWidget(),
        }

blog/views.py
from django.shortcuts import render
from django.views import generic
from blog.models import Post
from blog.forms import CommentForm
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, View
from .models import Post, PostCategory

# Create your views here.


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/allblogs.html'
    paginate_by = 3


def post_detail(request, slug):
    template_name = 'blog/post_detail.html'
    post = get_object_or_404(Post, slug=slug)
    query = Post.objects.filter(status=1)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form,
                                           'query':query})


def about_view(request):
    template_name = 'about.html'
    context = {}
    return render(request, template_name, context)


def service_view(request):
    template_name = 'services.html'
    context = {}
    return render(request, template_name, context)


class SearchPostCategoryView(ListView):

    template_name = "blog/allblogs.html"

    def get_queryset(self):
        model = Post

        self.category = get_object_or_404(
            PostCategory, name=self.kwargs['category'])
        return Post.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):

        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the publisher
        context['category'] = self.category
        return context

templates/blog/allblogs.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}Blogs{% endblock %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .shadow {
        box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
    }

    .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
    }

    .masthead {
        background: #3398E1;
        height: auto;
        padding-bottom: 15px;
        box-shadow: 0 16px 48px #E3E7EB;
        padding-top: 10px;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }

    .jumbotron {
        background: #358CCE;
        color: #FFF;
        border-radius: 0px;
    }

    .jumbotron-sm {
        padding-top: 24px;
        padding-bottom: 24px;
    }

    .jumbotron small {
        color: #FFF;
    }

    .h1 small {
        font-size: 24px;
    }
</style>


<div class="container">
    <div class="jumbotron jumbotron-sm">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-lg-12">
                    <h1 class="h1">
                        Our Blog <small>Fight the Fight, Find the Cure!</small></h1>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title|title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{ post.content | safe}}</p>
                    <a href="{% url 'blog:post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %}
        {% include 'blog/sidebar.html' %}
        {% endblock sidebar %}
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation conatiner"></nav>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

        {% endif %}
    </ul>
    {% endif %}
</div>
{% endblock content %}

templates/blog/blog_category_search.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}Blogs{% endblock %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .shadow {
        box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
    }

    .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
    }

    .masthead {
        background: #3398E1;
        height: auto;
        padding-bottom: 15px;
        box-shadow: 0 16px 48px #E3E7EB;
        padding-top: 10px;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>


<div class="container">
    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                        <p class="text-light">We Love Django As much as you do..! &nbsp
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{ post.content | safe}}</p>
                    <a href="{% url 'blog:post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %}
        {% include 'blog/sidebar.html' %}
        {% endblock sidebar %}
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation conatiner"></nav>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

        {% endif %}
    </ul>
    {% endif %}
</div>
{% endblock content %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% block head_title %}{{ post.title|title }}{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title|title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %}
    {% include 'blog/sidebar.html' with object_list=query %}
    {% endblock sidebar %}
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ comments.count }} comments</h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | safe | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {% csrf_token %}
          {{ comment_form.media }}
          {{ comment_form.as_p }}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
  {% endblock content %}

templates/blog/sidebar.html
{% block sidebar %}
{% load static %}
<style>
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
    <!-- Categories Widget -->
    <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-unstyled mb-0">
                        {% for post in object_list %}
                        <li>
                            <a href="{% url 'blog:post_list_by_category' post.category %}">{{post.category|title}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

            </div>
        </div>
    </div>

    <div class="card my-4">
        <h5 class="card-header">About Us</h5>
        <div class="card-body">
            <p class="card-text"> In Pharmecy.uz you can find many types of drugs easily and quickly. This project is
                able to give you all necessary information you’d want to. In addition...</p>
            <a href="{% url 'about' %}" class="btn btn-danger">Know
                more!</a>
        </div>
    </div>
</div>

{% endblock sidebar %}