blog/urls.py
from django.urls import path
from blog.views import post_detail, PostList, SearchPostCategoryView

# app_name

app_name = 'blog'

# Create your urls here.

urlpatterns = [
    path('', PostList.as_view(), name='allblogs'),
    path('<slug:slug>/', post_detail, name='post_detail'),
    path('category/<category>/', SearchPostCategoryView.as_view(), name='post_list_by_category'),
]

contact/urls.py
from django.urls import path
from contact.views import emailView, successView
# app_name
app_name = 'contact'

# Create your urls here.

urlpatterns = [
    path('email/', emailView, name='email'),
    path('success/', successView, name='success'),
]

core/urls.py
from django.urls import path
from core.views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

ecommerce_pharmacy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import about_view, service_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('search.urls', namespace='search')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('about/', about_view, name='about'),
    path('services/', service_view, name='services'),
    path('contact/', include('contact.urls', namespace='contact')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# django admin site custom header and title
admin.site.site_header = "PHARMACY::ONLINE STORE:: ADMIN"
admin.site.site_title  = "PHARMACY::ONLINE STORE:: ADMIN PORTAL"
admin.site.index_title = "WELCOME TO PHARMACY::ONLINE STORE:: ADMINISTRATION"

search/urls.py
from django.urls import path
from search.views import (
    SearchProductView,
    SearchCategoryView,
)

app_name = 'search'

urlpatterns = [
    path('s/', SearchProductView.as_view(), name='query'),
    path('category/<category>/', SearchCategoryView.as_view(), name='item_list_by_category'),
]

contact/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.db.models import Q

# Create your models here.

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('search:item_list_by_category', kwargs={
            'slug': self.slug
        })


class ItemQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)

    def category(self, query):
        return self.filter(active=True, category=query)

    def search(self, query):
        lookups = (Q(title__icontains=query) |
                   Q(description__icontains=query) |
                   Q(price__icontains=query) |
                   Q(category__name__icontains=query)
                   )

        return self.filter(lookups).distinct()


class ItemManager(models.Manager):
    def get_queryset(self):
        return ItemQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self):
        return self.get_queryset().featured()

    def get_by_id(self, id):
        # Product.objects == self.get_queryset()
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)

    def category(self, query):
        return self.get_queryset().category(query)


class Item(models.Model):
    title = models.CharField(max_length=120)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='items')
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    objects = ItemManager()

    class Meta:
        ordering = ('category',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

contact/forms.py
# make sure this is at the top if it isn't already
from django import forms

# our new form


class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True, widget=forms.EmailInput(
        attrs={'placeholder': 'Your Email',
               'class': 'form-control'}))
    subject = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'Your Subject',
               'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'Write your message here...',
               'class': 'form-control'}), required=True)
    # the new bit we're adding

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['from_email'].label = "Email:"
        self.fields['subject'].label = "Subject:"
        self.fields['message'].label = "Message:"

contact/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError
from contact.forms import ContactForm
from django.core.mail import EmailMessage
from django.template.loader import get_template


def emailView(request):
    template_name = 'contact.html'
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email,
                          ['pharmacy.uz@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('contact:success')
    return render(request, template_name, {'form': form})


def successView(request):
    return HttpResponse('Success! Thank you for your message.')

search/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.views.generic import ListView
from core.models import Item, Category

# Create your views here.


class SearchProductView(ListView):
    template_name = "search/view.html"

    def get_context_data(self, *args, **kwargs):
        context = super(SearchProductView, self).get_context_data(
            *args, **kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        method_dict = request.GET
        query = method_dict.get('q', None)
        if query is not None:
            return Item.objects.search(query)
        return Item.objects.featured()


class SearchCategoryView(ListView):

    template_name = "home.html"

    def get_queryset(self):
        model = Item

        self.category = get_object_or_404(
            Category, name=self.kwargs['category'])
        return Item.objects.filter(category=self.category, active=True)

    def get_context_data(self, **kwargs):

        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the publisher
        context['category'] = self.category
        return context

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block head_title %}Home{% endblock %}

{% block content %}
<main>
  <div class="container">
    <!--caurosel-->
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" role="listbox"
      style="width:100%; height: 500px !important;">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="{% static 'img/carousel/back (1).jpg' %}" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'img/carousel/back (5).jpg' %}" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'img/carousel/back (2).jpg' %}" alt="Third slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'img/carousel/back (6).jpg' %}" alt="Third slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'img/carousel/back (4).jpg' %}" alt="Third slide">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <!--caurosel-->
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'core:home' %}">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% for item in object_list %}
          <li class="nav-item">
            <a class="nav-link"
              href="{% url 'search:item_list_by_category' item.category %}">{{item.category|title}}</a>
          </li>
          {% endfor %}
        </ul>
        <!-- Links -->

        <form class="form-inline" action='{% url "search:query" %}' method="GET">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="q"
              value="{{ request.GET.q }}">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <div class="row wow fadeIn">

        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card">

            <div class="view overlay">
              {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg"
                class="card-img-top"> {% endcomment %}

              <img src="{{ item.image.url }}" class="card-img-top" width="100%" height="216px">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
              <img src="" alt="">
            </div>

            <div class="card-body text-center">
              <a href="{{ item.get_absolute_url }}" class="grey-text">
                <h5>{{ item.category|title }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title|title }}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                </strong>
              </h4>

            </div>

          </div>

        </div>
        {% endfor %}
      </div>

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

    <!-- Our Customers -->
    <h2>Our Pharmaceuticals Distributors</h2>
    <div class="row">
      <div class="col-lg-2 col-sm-4 mb-4">
        <a href="#">
          <img class="img-fluid" src="{% static 'img/distributors/1.png' %}" alt="">
        </a>
      </div>
      <div class="col-lg-2 col-sm-4 mb-4">
        <a href="#">
          <img class="img-fluid" src="{% static 'img/distributors/3.png' %}" alt=""></a>
      </div>
      <div class="col-lg-2 col-sm-4 mb-4">
        <a href="#">
          <img class="img-fluid" src="{% static 'img/distributors/4.jpg' %}" alt=""></a>
      </div>
      <div class="col-lg-2 col-sm-4 mb-4">
        <a href="#">
          <img class="img-fluid" src="{% static 'img/distributors/5.jpg' %}" alt=""></a>
      </div>
      <div class="col-lg-2 col-sm-4 mb-4">
        <a href="#">
          <img class="img-fluid" src="{% static 'img/distributors/6.gif' %}" alt="">
        </a>
      </div>
      <div class="col-lg-2 col-sm-4 mb-4">
        <a href="#">
          <img class="img-fluid" src="{% static 'img/distributors/7.jpg' %}" alt=""></a>
      </div>
    </div>
    <!-- /.row -->
  </div>
</main>
{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}
{% load static %}
{% load socialaccount %}
<style>
  .header {
    color: #ffffff;
    background-color: rgba(0, 0, 0, 0.10);
    padding: 10px 0;
    -webkit-transition: all 0.2s ease-in-out;
    -moz-transition: all 0.2s ease-in-out;
    -o-transition: all 0.2s ease-in-out;
    -ms-transition: all 0.2s ease-in-out;
    transition: all 0.2s ease-in-out;
  }
</style>
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <div class="container">
    
    <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/"><img id="logo" src="{% static 'img/logo8.png' %}" alt="pharmacy" width="35px" height="35px">
        <strong class="blue-text">Pharmacy.uz</strong>
      </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        {% comment %} 
        <li class="nav-item active">
          <a class="nav-link waves-effect" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
        </li> 
        {% endcomment %}

        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'services' %}">Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'contact:email' %}">Contact</a>
        </li>
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'blog:allblogs' %}">
            <span class="clearfix d-none d-sm-inline-block"> Blog </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">
            <span class="clearfix d-none d-sm-inline-block"> Login </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% provider_login_url 'google' %}">
            <span class="clearfix d-none d-sm-inline-block"> Log In with Gmail </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'blog:allblogs' %}">
            <span class="clearfix d-none d-sm-inline-block"> Blog </span>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base.html" %}
{% block head_title %}Order Summary{% endblock %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}